### PR TITLE
[CAM-11670] feat(auth): add keycloak auth interceptor

### PR DESCRIPTION
**Pull request by akkie**
[CAM-11670](https://app.camunda.com/jira/browse/CAM-11670)

This pull request adds a KeycloakAuthInterceptor on top of `got` hooks. Hooks
are supported since version 9 of `got` and they allow to use async functions
to manipulate the request. This pull request adds this functionality without
loosing backward compatibility. It also serves as an example of how authentication
against third party authentication providers can be implemented with hooks.

The complete code was updated to work with the latest version of `got`. The new
functionality is covered with tests.

### CODE REVIEW

**Comment by akkie** [comment]
OK, it brakes backward compatibility with Node 8. The `got` library in the newest version needs Node 10

**Comment by tmetzke** [comment]
Hi @akkie,

thanks for your extensive work on this!

We'll be looking into this as soon as possible to leave you a proper review and answer your questions in-depth.

Meanwhile, you can also track the progress on this in https://jira.camunda.com/browse/CAM-11670.

Best,
Tobias

**Comment by akkie** [comment]
Added the functionality to reuse valid tokens

**Comment by marstamm** [comment]
Hey @akkie ,

Your code looks very clean and well documented.

I have very little experience with keycloak and the server setup required. Could you give me some hints on how to setup a camunda application secured with keycloack so I can test it in action? Maybe you have an example Project already that I can have a look at.
That would be very appreciated.

Cheers
Martin

**Comment by akkie** [comment]
Hey @marstamm,

thank you! Unfortunately I don't have an example to share. But the setup should be straight forward. I think the best is it to setup with docker compose. There are docker images for Keycloak and Gatekeeper.

In front of the Camunda REST API, there must be a gatekeeper instance. You should disable the authentication for the REST API. We don't use the REST API provided by Camunda because it wasn't possible to integrate it in our Scala bases Play Framework application. So thanks to the awesome documentation, we have implemented the external task part of the API itself.

I can share a Screenshot of the Keycloak settings and the Gatekeeper configuration tomorrow.

**Comment by marstamm** [comment]
Hey @akkie ,

sorry for the long wait, but I got good news. To support this Feature, we can remove Node 8 support. We will release a new version so we do not break backwards compatibility for versions <=v1.3.

I was also able to secure my restAPI with keycloack and could try it out myself :tada: 
I will resolve the lockfile conflicts and merge the PR. 

Thank you for your patience :)

**Comment by akkie** [comment]
@marstamm Thanks 👍

**Pull request closed without merging**
