### PR TITLE
chore(deps): bump lodash to version 4.17.21

### PR DESCRIPTION
**Pull request by tasso94**
related to CAM-13489

### CODE REVIEW

**Review by marstamm — CHANGES_REQUESTED** [review]
It is unnecessary to have both `package-lock.json` and `yarn.lock` files. For the scope of this ticket, let's just update what is already there and not add additional package-lock files for `test/` and `/examples/*`. 

At one point, we should decide whether we want to use npm or yarn for this project. I got the feeling that the `package-lock.json` in the root directory was committed by accident a while back.

**Comment by tasso94** [comment]
I agree. Our CI uses npm and as a user, I'm free to choose npm or yarn. Do you care if we just remove the `yarn.lock` files? Like this, we don't need to handle both files when we want to bump dependencies.

**Comment by marstamm** [comment]
I like that idea, this way we can keep our dev environments the same across all projects.

**Review by marstamm — APPROVED** [review]
:100:

**Pull request merged**
