### PR TITLE
CAM-10229 Balancing for tasks consumption

### PR DESCRIPTION
**Pull request by litichevskiydv**
In stress conditions task execution time can vary uncontrollably and some tasks can be still run when `poll` consumes new portion. As a result, it may overload the worker.
The aim of this fix is to balance tasks consuming rate according to their processing speed.

### CODE REVIEW

**Comment by yanavasileva** [comment]
Hi @litichevskiydv ,

Thank you for your contribution.
We will evaluate the PR internally and get back to you as soon as possible.
You can keep a track of it in this Jira ticket:
https://app.camunda.com/jira/browse/CAM-10229

Best regards,
Yana

**Comment by yanavasileva** [comment]
Hi @litichevskiydv ,

We need more information in order to evaluate the PR.
Could you please give us an example of the scenario which you try to resolve.
The example will help to understand the scenario better and make a decision based on it.
We are interested in where the bottleneck seems to be according to your scenario. When the execution of the task is async and it leads to multiple created in parallel threads, so:
* Is it the problem for you the multiple parallel executions on the Client side only, what is the impact in that case?
* Or the problem is related that in the handler is called some API to external system/Camunda and the current implementation will send multiple requests to it which may cause problems on that system?
* Or something else, please elaborate further.

Best regards,
Yana

**Comment by litichevskiydv** [comment]
Hi @yanavasileva,
I'll describe the situation briefly. 

We have a service written in NodeJs which consumes external tasks, reads data from external storage and creates new processes in Camunda.
Camunda worker scheme

Current implementation of `Client` consumes `maxTasks` external tasks from Camunda every `interval` milliseconds. In our case in stress conditions performance of external storage degraded and tasks began to accumulate in the service because `Client` consumes the same amount of tasks every `interval`.
Camunda worker overload

Furthermore, after a while for some tasks `lockDuration` interval was exceeded and service began to consume them multiple times what made the situation worse. Finally external storage died because of huge amount of requests and service died too.

That is why I want to limit the speed of tasks consumption in accordance with their processing speed, to prevent the accumulation of tasks at the consumer.

**Comment by tasso94** [comment]
Hi @litichevskiydv,

thanks for your patience.

We are currently busy with the 7.11 release and will come back to you as soon as possible.

Cheers,
Tassilo

**Comment by litichevskiydv** [comment]
@marstamm, thank you for review! I have made necessary alterations, please, check code again.

**Pull request merged**
